external_components:
  - source:
      type: local
      path: external_components
    components: [gdk101]

esphome:
  name: radiation
  friendly_name: radiation
  on_boot:
    priority: -100
    then:
      - delay: 3s

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "/LjyNcObMHP9YuqwgbQsUBGtRSD2p7xlgTR6JhpMBcc="

ota:
  platform: esphome
  password: "16f35ec99f28a1d3ddf46e1093918bd2"

wifi:
  use_address: radiation.geier.solutions
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radiation Fallback Hotspot"
    password: "Yo8jC0ocHn4y"

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 50kHz

# Hub/Komponente (hier gehören address + update_interval hin)
gdk101:
  address: 0x18
  update_interval: 60s

sensor:
  - platform: gdk101
    radiation_dose_per_1m:
      name: "GDK101 Radiation Dose (1 min)"
    radiation_dose_per_10m:
      name: "GDK101 Radiation Dose (10 min)"
    status:
      name: "GDK101 Status"
    measurement_duration:
      name: "GDK101 Measuring Time"

binary_sensor:
  - platform: gdk101
    vibrations:
      name: "GDK101 Vibrations"

text_sensor:
  - platform: gdk101
    version:
      name: "GDK101 FW Version"

captive_portal: