# Your Wi-Fi SSID and password
wifi_ssid: "your_SSID"
wifi_password: "your_password"
wifi_ap_ssid: "your_ap_SSID"
wifi_ap_password: "your_ap_password"
api_key: "your_api_key"
ota_password: "your_ota_password"